### ISSUE TITLE
Do not install python package threedi-api-client

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/3Di-modeller-interface-installer#12]
If a user just downloads and runs the modeller interface installer, its python environment contains a (old) version of the threedi-api-client python package. This breaks the 3Di Models & Simulations plugin.

This is not 100% clear to me, but I have the impression that this is due to some configuration in the installer itself (not in one of the plugins). Please remove this python package from the installer.

**Comment by reinout** [comment]
If I do a textual search for the plugin, there's nothing in the installer, except that the plugin is switched off in a .ini file.
Isn't it bundled with the threeditoolbox?

Which (old) version? Which directory?

**Comment by leendertvanwolfswinkel** [comment]
This is not about the plugin. It is about the threedi-api-client _python package_. If you can confirm that this python package is not included in the install, I'd be happy.
