### ISSUE TITLE
Use customized QGIS settings also for new user profiles

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/3Di-modeller-interface-installer#17]
The 3Di Modeller Interface changes several QGIS settings. Some of these settings are required for correct behaviour of our plugins (e.g. for handling scientific notations of very small floats).

This is currently implemented by installing a pre-configured user profile called 'default'. However, if a user creates a new user profile, these customizations are not applied to that new user profile; the settings for a new user profile are read from (in my case) "C:\Program Files\3DiModellerInterface 3.22\apps\qgis-ltr\resources\qgis_global_settings.ini". This is documented here: https://docs.qgis.org/3.22/en/docs/user_manual/introduction/qgis_configuration.html#deploying-qgis-within-an-organization

I propose to change our implementation in such a way that all the settings we now set in `qgis.ini` are moved to `qgis_global_settings.ini`

**Comment by benvanbasten-ns** [comment]
The settings in the specified file replace the original inline default ones, but the user profiles’ settings will be set on top of those.

**Comment by leendertvanwolfswinkel** [comment]
Does this have any consequences for the usability of this approach for our aims? Do you need any input/decision from me? Or are these just technical notes-to-self?

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel The global settings file can be used, but it does not add settings to a new qgis.ini. 

QgsSettings basically work with a fallback mechanism. If a setting is not present in the users' qgis.ini, it will check whether it exists in qgis_global_settings.ini, if it doesn't exist there, it will use the default value in the code. 

We can set the import settings in the global settings, and if the user doesn't change them, he should probably use the correct settings. Would that be a good idea?
