### ISSUE TITLE
create persistent breaches

### ISSUE THREAD

**Issue by Jonasvsl** [nens/3Di-modeller-interface-installer#19]
https://nelenschuurmans-my.sharepoint.com/:w:/g/personal/jonas_vanschrojenstein_nelen-schuurmans_nl/EeGZMH0BicRPl7UKYWyisrkBGbxZXKL-D4D2jfAssB5AAg?e=9nA08a

Excerpt from the document above:

The current implementation for schematizing breaches is confusing, difficult to explain and difficult to use in practice. Reasons for this is that many steps are needed to create a breach, it is not very visual (not what you see is what you get) and changing unrelated parts of the schematization often required recreating all existing breaches. 

This document proposes a new way of schematizing breaches that should solve those problems. 

This proposal has been set up with the assumption that no (major) changes to the computational core are required. It does not include 2D/2D breaches. 

The schematisation of breaches is related to how 1D/2D connections are schematised in general. This is especially relevant for “double connected”. 

User story / requirements 

Modellers want to be able to: 

- Add breaches by drawing it on the map canvas 
- Add breaches automatically at specified intervals along a levee 
- Add breaches automatically at specific point locations on a levee 
- When adding breaches automatically, specify which breaches and levees should be taken into consideration by the algorithm 
- Add breaches in at one side or both sides in case there are levees at both sides of the channel 
- Be able to choose where the breach connects to the 2D domain 
- See on the map canvas how a breach connects channels to the 2D domain 
- See on the map canvas how the schematization of the breach is interpreted when generating the computational grid 
- Label breaches with a name or code that stays the same from one revision to the next 
- Change other part of the schematization without having to re-create the breaches 

[User stories that may require changes to computational core:] 

Add a breach over a levee that has a boundary condition at the upstream side instead of a channel

**Comment by leendertvanwolfswinkel** [comment]
This is now an Epic in zenhub, no need for this to be a ticket anymore
