### ISSUE TITLE
count number 1D-2D connections in a calculation cell

### ISSUE THREAD

**Issue by Jonasvsl** [nens/3Di-modeller-interface-installer#24]

**Comment by Jonasvsl** [comment]
not sure if this can be in the checker but we need to have a warning in case there are more than X 1D-2D connections in the same computational cell.

Let's discuss with Nici what would be a treshold value

**Comment by caspervdw** [comment]
Issue moved to [nens/threedigrid-builder #264](https://github.com/nens/threedigrid-builder/issues/264) via [**Zenhub**](https://www.zenhub.com/)
