### ISSUE TITLE
Create test version of 3Di MI installer based on QGIS 3.28

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/3Di-modeller-interface-installer#25]
De installer voor QGIS 3.28 is deze week gereleased. Deze versie wordt in februari de nieuwe Long Term Release. Ik zou graag een MI installer willen hebben op basis van QGIS 3.28, zodat van nov t/m februari getest kan worden of alles naar behoren werkt. 

Deze versie kan dan in maart 2023 gereleased worden.

**Comment by benvanbasten-ns** [comment]
https://docs.3di.live/modeller-interface-downloads/3DiModellerInterface-OSGeo4W-3.28.0-2-0-Setup-x86_64.exe

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel can be tested
