### ISSUE TITLE
Remove space in App name

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/3Di-modeller-interface-installer#26]
After installation, the app is known to Windows as "3DiModellerInterface 3.xx" Please change this to "3Di Modeller Interface 3.xx", so that users can find the app in windows if they type "3Di Modeller Interface" in the search bar

![image](https://user-images.githubusercontent.com/26224299/201664827-64852c6b-24f5-4145-ab56-d70d27e7e409.png)

**Comment by benvanbasten-ns** [comment]
This is the name of the shortcut (.lnk file)
