### ISSUE TITLE
Multi-user installer

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/3Di-modeller-interface-installer#36]
**Option 1** System admin installs 3Di Modeller Interface, users install profile on first use
- [ ] Installer also creates shortcuts in user profile (move from first install option to second install section), with correct arguments (--profile-folder "C:\...\user.name\blablabla")

**Option 2** Include option to "install for all users" in installer
- [ ] Research options for this in windows installers; would this work correctly with references to profile folders etc.?

**Option 3** Ask Wolf how this is done for Nelen & Schuurmans Consultancy
- [ ] ... 

**Option 999**: Use 'public' profile on windows, QGIS user profile for each user (not preferred)

**Short-term workaround**, like option 1: admin installs 3Di MI; copies shortcut to public or shared location, user copies the .lnk file and changes --profile-folder argument to the correct value for that user

**Comment by benvanbasten-ns** [comment]
C:\Users\Public\Desktop

**Comment by leendertvanwolfswinkel** [comment]
Feedback from testing:
- [ ] Typo ("3D" instead of "3Di") 
![image](https://user-images.githubusercontent.com/26224299/230045225-7970b7b9-c308-494c-ab42-f46f625b65be.png)

**Comment by benvanbasten-ns** [comment]
Also moved the "Choose Install Location" section behind "Choose Components" section
