### ISSUE TITLE
pyqtgraph plots messed up on second screen

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/3Di-modeller-interface-installer#37]
Suggested solution is to include some QT global settings in the .bat file that start QGIS

@benvanbasten-ns please add details on the solution you had in mind to this ticket

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel added this issue to the Toolbox/results analysis epic so we won't overlook this.

**Comment by benvanbasten-ns** [comment]
https://github.com/qgis/QGIS/issues/49764#issuecomment-1601901536

Might get solved in QGIS 3.32

**Comment by benvanbasten-ns** [comment]
Solved in 3.32

3.28.7 Firenze

![image](https://github.com/nens/3Di-modeller-interface-installer/assets/97883955/b39e72b2-f037-42e8-9c5c-7e95fbaf03e6)

3.32.0 Lima

![image](https://github.com/nens/3Di-modeller-interface-installer/assets/97883955/94e0877e-08a0-4b9a-bff9-b6518075b0a5)
