### ISSUE TITLE
include plugin hydx in profile

### ISSUE THREAD

**Issue by Jonasvsl** [nens/3Di-modeller-interface-installer#6]
is it possible to include this plugin in the modeller interface profile?

https://github.com/threedi/beta-plugins/tree/master/import_hydx

@RichardB9 
What needs to happen to make that possible?

**Comment by RichardB9** [comment]
Do you only want to include it in the modeller interface? Or also in the ThreediToolbox?

If we want to include it in the ThreediToolbox we could integrate it similar as threedidepth and the threedi-modelchecker: as a separate python package available via a processing plugin. In that case the plugin must become a python-package and be released on pypi. Furthermore we need to write a Processing algorithm which uses the package.

Another way would be to include all the code into the 3Di-modeller-interface installer. This is faster but then requires more work everytime the plugin gets updated. In that case need to copy over the new version of the plugin.

**Comment by leendertvanwolfswinkel** [comment]
will be included in upcoming release of 3Di Toolbox
