### ISSUE TITLE
new MSI instead of NSIS installers

### ISSUE THREAD

**Issue by Jonasvsl** [nens/3Di-modeller-interface-installer#8]
Does this:
https://twitter.com/juergenefischer/status/1406990156431859716?s=27

mean that we need to rewrite the installer creation process?

**Comment by Patrick-Nijman** [comment]
Linux, Mac and Windows packages of new release candidate #QGIS 3.20.0 'Odense' and point release of 3.16.8 'Hannover' (LTR) ready on http://qgis.org.  For Windows also see the second post. Enjoy! 

#OSGeo4W testing was promoted to v2. Complete overhaul. No 64bit.  Upgrades from old OSGeo4W not supported. Do a fresh install.  Standalone installers now MSI.  QGIS LTR is also still available in old OSGeo4W based on the old dependencies plus NSIS standalone installers. 2/2

**Comment by leendertvanwolfswinkel** [comment]
Fixed in the new 'wrapper' setup of the MI installer
